spot:
  controller_manager:
    ros__parameters:
      update_rate: 10  # Hz
      joint_trajectory_position_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      joint_states_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  joint_trajectory_position_controller:
    ros__parameters:
      joints:
        - joint_front_left_shoulder
        - joint_front_left_leg
        - joint_front_left_foot
        - joint_front_right_shoulder
        - joint_front_right_leg
        - joint_front_right_foot
        - joint_rear_left_shoulder
        - joint_rear_left_leg
        - joint_rear_left_foot
        - joint_rear_right_shoulder
        - joint_rear_right_leg
        - joint_rear_right_foot
      command_interfaces:
        - position
      state_interfaces:
        - position
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      open_loop_control: true
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.0
        # front_left_shoulder:
        #   trajectory: 0.05
        #   goal: 0.03
        # front_left_leg:
        #   trajectory: 0.05
        #   goal: 0.03
        # front_left_foot:
        #   trajectory: 0.05
        #   goal: 0.03
        # front_right_shoulder:
        #   trajectory: 0.05
        #   goal: 0.03
        # front_right_leg:
        #   trajectory: 0.05
        #   goal: 0.03
        # front_right_foot:
        #   trajectory: 0.05
        #   goal: 0.03
        # rear_left_shoulder:
        #   trajectory: 0.05
        #   goal: 0.03
        # rear_left_leg:
        #   trajectory: 0.05
        #   goal: 0.03
        # rear_left_foot:
        #   trajectory: 0.05
        #   goal: 0.03
        # rear_right_shoulder:
        #   trajectory: 0.05
        #   goal: 0.03
        # rear_right_leg:
        #   trajectory: 0.05
        #   goal: 0.03
        # rear_right_foot:
        #   trajectory: 0.05
        #   goal: 0.03
